### ISSUE TITLE
Stops working after computer locks

### ISSUE THREAD

**Issue by dfpera** [mre/timelapse#32] opened 2020-01-04 00:20 UTC
Tried to do a timelapse of my day at work, however, when I went off to a meeting and closed my laptop screen the recording did not resume when I logged back in.

## Describe the Bug

Recording stops when computer locks. When logging back in, the screenshots stop occurring and when "Stop Recording" is selected from menubar, the app stops responding. No video is output as I have to force quit.

**Comment by mre** [comment] 2020-01-05 13:22
Ouch. That's bad and I'm sorry for the inconvenience. I'll try to look into it and see if I can find a fix.

**Comment by mre** [comment] 2020-01-19 18:36
Tried to reproduce and it works for me. Can you try the lastest version @dfpera?
You can find it on the release page. 😊

**Comment by mre** [comment] 2020-01-31 15:44
I'll go ahead and close this to keep the bug-tracker clean; assuming this works now.

**Closed by mre** 2020-01-31 15:44 UTC
Labels: feedback-wanted
